### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by jayvdb** [pybee/slick#1]
While unlikely to be a problem, this conflicts with another project: https://pypi.org/project/slick/

It would be nice if this was on pypi, even in alpha stage.

**Comment by freakboy3742** [comment]
This isn't a name conflict in practice; firstly, because slick is a toy application, not something serious; but also because it's a user-space application, not something you'd install from PyPI. The distribution mechanism for this would be an App Store, (or a website with a download link for an installer), not PyPI
